spring:
  application:
    name: good-restaurant
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate  # to prevent accidental schema changes in production-databases
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

server:
  forward-headers-strategy: framework   # for https behind a proxy

## naver api key - 네이버 지오코딩용 API
naver:
  geocode:
    base-url: ${NAVER_GEOCODE_BASE_URL}
    client-id: ${NAVER_GEOCODE_CLIENT_ID}
    client-secret: ${NAVER_GEOCODE_CLIENT_SECRET}