spring:
  application:
    name: good-restaurant
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  config:
    import: optional:file:.env[.properties]
  jpa:
    hibernate:
      ddl-auto: validate  # to prevent accidental schema changes in production-databases
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
        default_batch_fetch_size: 1000
  servlet:
# multipart MAX size is 500 MB, but CF-max-upload is 100MB
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  forward-headers-strategy: framework   # for https behind a proxy
  port: 8080

## naver api key - 네이버 지오코딩용 API
naver:
  geocode:
    base-url: ${NAVER_GEOCODE_BASE_URL}
    client-id: ${NAVER_GEOCODE_CLIENT_ID}
    client-secret: ${NAVER_GEOCODE_CLIENT_SECRET}


s3object:
  object-server-url: "https://s3api.i4624.info"

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG     ## 웹 요청 처리 과정
    org.springframework.web.client: DEBUG  ## RestTemplate 요청/응답
    org.apache.http: DEBUG            ## Apache HttpClient 기반이면
    okhttp3: DEBUG                    ## OkHttp 기반이면 (Spring Cloud/OpenFeign 등)
    com.good_restaurant: DEBUG         ## 내 패키지

  include:
    - http

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sso.i4624.info/realms/i4624sso